---
language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - choco install saltminion
        - export PATH="/c/salt:$PATH"
        - python -m pip install --upgrade pip wheel

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./build/install_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy RemoteSigned ./build/install_windows.ps1; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash ./build/script_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell -ExecutionPolicy RemoteSigned ./build/script_windows.ps1; fi
